### ISSUE TITLE
Unrecognized character

### ISSUE THREAD

**Issue by achinastone** [marat1961/protobuf-delphi#9]
In my computer. I have the source code as follow:
`procedure TGen.GenComment(const ? string);`
`var`
`  s: string;`
`begin`
`  for s in ?Split([#13#10], TStringSplitOptions.None) do`
`    Wrln('// ' + s)`
`end;`

**Comment by marat1961** [comment]
Corrected.
At this point in the code, I typed the Russian letter c, which on the keyboard is in the same place as the Latin c and visually is no different.
